### ISSUE TITLE
the output of fct_collapse(..., `group_other = TRUE)  seems wrong order.

### ISSUE THREAD

**Issue by cuttlefish44** [tidyverse/forcats#219] opened 2019-11-08 11:05 UTC
When I use `fct_collapse`  with `group_other = TRUE`, the output are not in correct order. Is this by design ?

``` r
library(forcats)

factor_vec <- as.factor(LETTERS[c(5,1,2,4,3)])

a <- fct_collapse(factor_vec,
                  BD = c("B", "D"),
                  ACE = c("A", "C", "E"))

b <- fct_collapse(factor_vec,
                  BD = c("B", "D"),
                  AC = c("A", "C"),
                  group_other = TRUE)

data.frame(origin = factor_vec, all_lev_named = a, with_group_other = b)
#>   origin all_lev_named with_group_other
#> 1      E           ACE            Other
#> 2      A           ACE               BD
#> 3      B            BD               BD
#> 4      D            BD               AC
#> 5      C           ACE               AC
```

<sup>Created on 2019-11-08 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by xjlc** [comment] 2019-11-16 01:15
I agree, also encountered this problem. 

For the maintainers: since `fct_other` seems to work, couldn't that be used as a fix?

I'm not deep enough in the code to fix it myself and don't really have the time to test this, but Instead of 
```
if (group_other) {
    f <- check_factor(.f)
    levels <- levels(f)
    new[["Other"]] <- levels[!levels %in% levs]
    levs <- c(levs, new[["Other"]])
}
...
if (group_other) {
    fct_relevel(out, "Other", after = Inf)
  } else {
    out
 }
```
something like this (maybe with the conditional moved to the top of the function?)
```
 if (group_other) {
   .f <- fct_other(.f)
}
...
out
```

**Comment by mjanson** [comment] 2020-01-16 17:19
Sorry if this is unrelated, but I figured it would be better to ask here first before opening a new issue:

`
> titles$Title
 [1] Mr     Mrs    Miss   Mrs    Mr     Mr     Mr     Master Mrs    Mrs   
Levels: Master Miss Mr Mrs
> fct_collapse(titles$Title, Mr = "Mr", group_other=TRUE)
 [1] Other Other Other Other Other Other Other Mr    Other Other
Levels: Mr Other
> packageVersion("forcats")
[1] ‘0.4.0’
>
`

**Comment by mstr3336** [comment] 2020-01-21 05:54
Weirdly enough, I remember seeing this a while ago, in #172 , and #202 .

We see it "fixed" (as of 0.4.0, according to the changelog apparently ) here:

https://github.com/tidyverse/forcats/commit/34ad9e558e1a903896531e7ca6eec0520a7d8349#diff-8312ad0561ef661716b48d09478362f3

That change was pushed in september, however, and the cran release of forcats 0.4.0 was: **2019-02-17** .

```r
> packageVersion("forcats")
[1] ‘0.4.0.9000’

> system.file("NEWS.md", package = "forcats") %>% readLines() %>% cat(sep = "\n")
# forcats (development version)

* `first2()`, a `fct_reorder2()` helper function, sorts `.y` by the first value of `.x` (@jtr13).

# forcats 0.4.0

## New features

* `fct_collapse()` gains a `group_other` argument to allow you to group all 
  un-named levels into `"Other"`. (#100, @AmeliaMN)
  
* fixed bug in `fct_collapse()` so it now correctly collapses factors when `group_other = TRUE` (#172), and makes `"Other"` the last level (#202) (@gtm19, #172 & #202)

* `fct_cross()` creates a new factor containing the combined levels from two 
  or more input factors, similar to `base::interaction` (@tslumley, #136)

* `fct_inseq()` reorders labels in numeric order, if possible (#145, @kbodwin).

* `fct_lump_min()` preserves levels that appear at least `min` times (can also 
  be used with the `w` weighted argument) (@robinsones, #142).

* `fct_match()` performs validated matching, providing a safer alternative to
  `f %in% c("x", "y")` which silently returns `FALSE` if `"x"` or `"y"` 
  are not levels of `f` (e.g. because of a typo) (#126, @jonocarroll).

* `fct_relevel()` can now level factors using a function that is passed the
  current levels (#117).

* `as_factor()` now has a numeric method. By default, orders factors in numeric 
  order, unlike the other methods which default to order of appearance. 
  (#145, @kbodwin)

## Minor bug fixes and improvements

* `fct_count()` gains a parameter to also compute the proportion 
  (@zhiiiyang, #146). 

* `fct_lump()` now does not change the label if no lumping occurs 
  (@zhiiiyang, #130). 

* `fct_relabel()` now accepts character input.

* `fct_reorder()` and `fct_reorder2()` no longer require that the summary 
  function return a numeric vector of length 1; instead it can return any
  orderable vector of length 1 (#147).

* `fct_reorder()`, `fct_reorder2()` and `as_factor()` now use the ellipsis
  package to warn if you pass in named components to `...` (#174).

# forcats 0.3.0

## Etcetera
```

**Comment by mstr3336** [comment] 2020-01-21 07:05
This is a weirdly hard bug to reproduce - I get the same (incorrect) output when I run @cuttlefish44 's reprex, but when I try to reproduce this with other examples, they sometimes work correctly

**Comment by gtm19** [comment] 2020-01-21 07:42
@cuttlefish44 @xjlc @mjanson: this bug is fixed in the development version of `forcats`:

``` r
library(forcats)

packageVersion("forcats")
#> [1] '0.4.0.9000'

factor_vec <- as.factor(LETTERS[c(5,1,2,4,3)])

a <- fct_collapse(factor_vec,
                  BD = c("B", "D"),
                  ACE = c("A", "C", "E"))

b <- fct_collapse(factor_vec,
                  BD = c("B", "D"),
                  AC = c("A", "C"),
                  group_other = TRUE)

data.frame(origin = factor_vec, all_lev_named = a, with_group_other = b)
#>   origin all_lev_named with_group_other
#> 1      E           ACE            Other
#> 2      A           ACE               AC
#> 3      B            BD               BD
#> 4      D            BD               BD
#> 5      C           ACE               AC
```

<sup>Created on 2020-01-21 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

You can install as follows:

`devtools::install_github("tidyverse/forcats")`

@mstr3336 As you can see, I get the correct output using `forcats 0.4.0.9000`, but the incorrect output with `0.4.0`. The issue _was_ fixed in the development version, but due to some confusion as (on my part) as to whether it would make it into 0.4.0, I added the `NEWS` item under the wrong heading. It should be under **forcats (development version)**. Apologies. I have created a pull request (#229) to fix this.

**Closed** 2020-01-21 15:50 UTC
