### ISSUE TITLE
Feature request: new function that expands and then relevels

### ISSUE THREAD

**Issue by netique** [tidyverse/forcats#271] opened 2020-08-16 11:39 UTC
It is very tedious to write `fct_relevel`, only to obtain an error stating that some level do not exist so I have to rewrite the line again with `fct_expand` first, piping into `fct_relevel` with the desired factors:

```
f <- factor("a", "b", "d")
f %>% fct_relevel("a", "b", "c", "d")
```

Leads to:
```
Warning message:
Unknown levels in `f`: c 
```

Whenever I work with factors, I am used to create and use this function instead of `fct_relevel`:
```
fct_exprel <- function(f, ...) {
  expanded <- forcats::fct_expand(f, ...)
  forcats::fct_relevel(expanded, ...)
}
```

I think something similar shlould be implemented in `forcats`. It does not interfere with any of `forcats` functions, user would use it with the explicit intention knowing what it does (better than modifying existing `fct_relevel`, e.g.).

**Comment by hadley** [comment] 2022-03-02 15:39
Duplicate of #287

**Closed by hadley** 2022-03-02 15:39 UTC
Labels: feature
