### ISSUE TITLE
add a logical method to as_factor

### ISSUE THREAD

**Issue by VincentGuyader** [tidyverse/forcats#211] opened 2019-09-26 22:02 UTC
The goal is to avoid this kind of error message :

``` r
forcats::as_factor(logical())
#> Error in UseMethod("as_factor"): pas de méthode pour 'as_factor' applicable pour un objet de classe "logical"
```

<sup>Created on 2019-09-27 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

I think that a good way to solve this is to use : 

```
as_factor.logical <- function(x,...){
  as_factor(as.character(x))
}
```

**Comment by hadley** [comment] 2020-01-21 16:47
Duplicate of #185

**Closed by hadley** 2020-01-21 16:47 UTC
Labels: feature
