### ISSUE TITLE
feature request:  function to convert factor to character

### ISSUE THREAD

**Issue by markdanese** [tidyverse/forcats#63] opened 2016-11-30 14:48 UTC
`as.character()` does not convert a factor to its character equivalent by using the factor level.  To do so is not obvious.  But it would be nice to have a function that does it to make it easier.  There is a stackoverflow answer on this:  http://stackoverflow.com/a/15554451/1720653 with a number of options including the one I like and highlighted:  `fact_character <- levels(fact)[as.numeric(fact)]`

**Comment by vspinu** [comment] 2016-12-06 19:05
You probably mean the other way around: function to convert factors with numeric levels to numbers.  

The implementation of `as.character.factor` is precisely what you want:

```R
> as.character.factor
function (x, ...) 
levels(x)[x]
<bytecode: 0x2d358c8>
<environment: namespace:base>
> as.character(factor(LETTERS))
 [1] "A" "B" "C" "D" "E" "F" "G" "H" "I" "J" "K" "L" "M" "N" "O" "P" "Q" "R" "S" "T" "U" "V" "W" "X" "Y" "Z"
```

The other way around is more tricky:

```R
> x <- as.factor(10:20)
> x
 [1] 10 11 12 13 14 15 16 17 18 19 20
Levels: 10 11 12 13 14 15 16 17 18 19 20
> as.numeric(x)
 [1]  1  2  3  4  5  6  7  8  9 10 11
> as.numeric(levels(x)[x])
 [1] 10 11 12 13 14 15 16 17 18 19 20
```

**Comment by markdanese** [comment] 2016-12-06 20:23
@vspinu -- thank you.  You are correct.

**Comment by hadley** [comment] 2016-12-30 15:20
Duplicate of #18

**Closed by hadley** 2016-12-30 15:20 UTC

**Comment by hadley** [comment] 2016-12-30 16:09
Ooops, #18 actually does something else. 

However, I don't want to support this operation. If you have a numeric vector that has somehow ended up as a factor, you are better off fixing the problem upstream in the data import step.
