### ISSUE TITLE
fct_cross does not preserve level ordering

### ISSUE THREAD

**Issue by kbodwin** [tidyverse/forcats#225] opened 2019-12-20 01:43 UTC
Very related to #183 .

`fct_cross` relevels factors after pasting, thus ordering them in alphabetical order.  

When you set `keep_empty = TRUE`, however, the original levels are preserved.  

``` r
library(forcats)

f1 <- c("a", "b", "c")
f2 <- c("alpha", "beta", "gamma")

f1 <- factor(f1, levels = c("b", "c", "a"))

fct_cross(f1, f2)
#> [1] a:alpha b:beta  c:gamma
#> Levels: a:alpha b:beta c:gamma

fct_cross(f1, f2, keep_empty = TRUE)
#> [1] a:alpha b:beta  c:gamma
#> 9 Levels: b:alpha c:alpha a:alpha b:beta c:beta a:beta ... a:gamma
```

<sup>Created on 2019-12-19 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by hadley** [comment] 2020-01-21 15:55
I think this is just a duplicate of #183

**Closed by hadley** 2020-01-21 15:55 UTC
